version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/golang-repo-template
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
      DOCKER_IMAGE: moul/golang-repo-template

orbs:
  codecov: codecov/codecov@1.0.5
  moul: moul/build@1.3.0

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - moul/install_retry
      - run: /tmp/retry -m 3 go mod download
      - run: /tmp/retry -m 3 make install
      - run: /tmp/retry -m 3 make test
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin /tmp/retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

  docker-build:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - moul/install_retry
      - run: /tmp/retry -m 3 docker build -t ${DOCKER_IMAGE} .

workflows:
  main:
    jobs:
      - go-build
      - docker-build
