version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/golang-repo-template
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
      DOCKER_IMAGE: moul/golang-repo-template

  docker:
    docker:
      - image: docker:18.06.3-ce-git

orbs:
  codecov: codecov/codecov@1.0.5
  moul: moul/build@1.5.0
  retry: moul/retry@0.6.0
  docker: circleci/docker@0.5.13
  #dl: moul/dl@1.7.0
  tools: gotest/tools@0.0.10

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - retry/install
      - tools/mod-download
      - tools/mod-tidy-check
      - run: retry -m 3 make install
      - run: retry -m 3 make unittest
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

  docker-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/build:
          image: moul/golang-repo-template
      #- docker/dockerlint

workflows:
  main:
    jobs:
      - go-build
      - docker-build
